#!/bin/python

import subprocess
import tempfile
import os

SUBMIT_FILES = {
    'A1': [
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/analysis/LiveVariableAnalysis.java',
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/solver/Solver.java',
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/solver/IterativeSolver.java',
    ],
    'A2': [
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/analysis/constprop/ConstantPropagation.java',
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/solver/Solver.java',
        'tai-e/src/main/java/pascal/taie/analysis/dataflow/solver/WorkListSolver.java',
    ],
}

def compress(hw):
    temp_dir = tempfile.mkdtemp()
    subprocess.run(["mkdir", "-p", f"{temp_dir}/{hw}/"])
    for src in SUBMIT_FILES[hw]:
        subprocess.run(["cp", f"{hw}/{src}", f"{temp_dir}/{hw}/"])
    files = list(map(lambda f: f"{temp_dir}/{hw}/{os.path.basename(f)}", SUBMIT_FILES[hw]))
    subprocess.run(["zip", "-j", f"{hw}.zip", *files])
    
for hw in SUBMIT_FILES:
    compress(hw)
